#!/bin/bash
sudo pacman -S openbox oblogout obconf python2-xdg lxterminal lxpanel leafpad plokit-gnome gnome-keyring lxrandr lxpanel lxappearance-obconf networkmanager network-manager-applet firefox flashplugin lxdm cantarell-fonts xdg-user-dirs dosfstools ntfs-3g gvfs gnome-themes-standard p7zip unzip zip unrar gtk-engine-murrine synapse wget

mkdir -p .config/openbox
cp -r /etc/xdg/openbox/* .config/openbox

sudo systemctl enable NetworkManager
sudo systemctl enable lxdm
